#!/bin/bash
## Tests

# Tests for arguments
# Check num of arguments - OK!
echo "arg = 1: should show 1"
./sfor

echo "arg = 2: should show 2"
./sfor 1

echo "arg = 3: should show 3"
./sfor 1 2

echo "Should ask to specify dir"
./sfor 1 2 3
echo "-d last arg. Should ask to specify dir"
./sfor 1 2 -d

echo "Should show arg < 4"
./sfor -d ./skilling_j

echo "Should show dir not found"
./sfor main -d ./home

echo "Help invoked. Should show syntax."
./sfor --help
./sfor -h

# echo "Print search terms"
# echo "Should print: lost sound mast"
# ./sfor -a lost sound mast -d /
# ./sfor -d / -a lost sound mast
# ./sfor -a -d / lost sound mast
# ./sfor lost -a -d / sound mast
# ./sfor lost -a sound -d / mast
# ./sfor lost -d / -a sound mast

# echo "Should print help"
# ./sfor lost -d / --help -h -a sound mast
# ./sfor lost -d / --help sound mast

# # Check dir
# echo "  Should print dir"
# ./sfor lost sound -d /
# echo "  Should print dir"
# ./sfor lost sound -d ~/bin
# echo "  Should print dir"
# ./sfor lost -d //mnt/42324F4B324F4361/PC\ Documents/01\ -\ Jeri/Software\ Dev/Yosemite\ Labs/skilling-j
# echo "  Should show not found"
# ./sfor lost -d ~/bi
