#!/bin/bash
## Tests

# Tests for arguments
# Check num of arguments - OK!
echo "arg = 1: should show 1"
./sfor

echo "arg = 2: should show 2"
./sfor 1

echo "arg = 3: should show 3"
./sfor 1 2

echo "Should ask to specify dir"
./sfor 1 2 3
echo "-d last arg. Should ask to specify dir"
./sfor 1 2 -d

echo "Should show arg < 4"
./sfor -d ./skilling_j

echo "Should show dir not found"
./sfor main -d ./home

echo "Help invoked. Should show syntax."
./sfor --help
./sfor -h